name: Deploy Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag da imagem Docker
        default: latest
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy no Kubernetes
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_B64 }}
        run: |
          echo "$KUBE_CONFIG" | base64 -d > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig
          kubectl apply -f k8s/ -n oficina
          kubectl set image deployment/oficina-os-service \
            oficina-os-service=ghcr.io/ricartefelipe/oficina-os-service:${{ inputs.image_tag }} \
            -n oficina
          kubectl rollout status deployment/oficina-os-service -n oficina --timeout=120s
